services:
   db:
      image: postgres:latest
      container_name: postgres-t-acerco
      restart: always
      ports:
         - '5435:5432'
      environment:
         POSTGRES_DB: t-acerco-db
         POSTGRES_USER: postgres
         POSTGRES_PASSWORD: postgres
   pgadmin:
      container_name: pgadmin-t-acerco
      image: dpage/pgadmin4:latest
      restart: always
      ports:
         - '5050:80'
      environment:
         PGADMIN_DEFAULT_EMAIL: admin@tacerco.dev
         PGADMIN_DEFAULT_PASSWORD: admin1404
